name: Deploy Angular app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Build the project
        run: npm run build -- --output-path=dist/mangooo.live/browser
        working-directory: ./app

      - name: Move built files to root
        run: |
          mkdir temp-gh-pages
          mv dist/mangooo.live/browser/* temp-gh-pages/
        working-directory: ./app

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=temp-gh-pages --no-silent --name="mangooo.live-deployment" --email="deployment@mangooo.live"
        working-directory: ./app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up temporary directory
        run: |
          rm -rf temp-gh-pages
        working-directory: ./app
